"""
IDE Rules Auto-Generator
Automatically generate .cursorrules, .trae/rules.md. PROJECT_RULES.md
"""

import os
from typing import Dict, List, Optional
from datetime import datetime


class IDERulesGenerator:
    """
    IDE Rules Auto-Generator
    
    Generates rules files for different IDEs:
    - .cursorrules (Cursor)
    - .trae/rules.md (Trae)
    - .github/copilot-instructions.md (Copilot)
    - PROJECT_RULES.md (Project)
    """
    
    RULES_FILES: Dict[str, str] = {
        "cursor": ".cursorrules",
        "trae": ".trae/rules.md",
        "copilot": ".github/copilot-instructions.md",
        "project": "PROJECT_RULES.md",
    }
    
    def __init__(self, storage, project_path: str = None):
        self.storage = storage
        self.project_path = project_path or os.getcwd()
    
    def update_rules(self):
        """Update all rules files"""
        rules = self.extract_rules_from_memories()
        
        for ide, filepath in self.RULES_FILES.items():
            content = self.format_rules(rules, ide)
            self.write_rules_file(filepath, content)
    
    def extract_rules_from_memories(self) -> Dict[str, List[str]]:
        """Extract rules from memories"""
        rules = {
            "tech_stack": [],
            "decisions": [],
            "patterns": [],
            "constraints": [],
            "todos": [],
        }
        
        # Extract tech stack
        tech_memories = self.storage.search("", limit=100)
        for mem in tech_memories:
            mem_type = mem.get("type", "")
            content = mem.get("content", "")
            
            if mem_type == "tech_stack":
                rules["tech_stack"].append(content)
            elif mem_type == "decision":
                rules["decisions"].append(content)
            elif mem_type == "pattern":
                rules["patterns"].append(content)
            elif mem_type == "constraint":
                rules["constraints"].append(content)
            elif mem_type == "todo":
                rules["todos"].append(content)
        
        return rules
    
    def format_rules(self, rules: Dict[str, List[str]], ide: str) -> str:
        """Format rules for specific IDE"""
        if ide == "cursor":
            return self.format_cursor_rules(rules)
        elif ide == "trae":
            return self.format_trae_rules(rules)
        elif ide == "copilot":
            return self.format_copilot_rules(rules)
        else:
            return self.format_project_rules(rules)
    
    def format_cursor_rules(self, rules: Dict[str, List[str]]) -> str:
        """Generate .cursorrules format"""
        content = "# Project Rules (Auto-generated by OpenMem)\n\n"
        
        if rules["tech_stack"]:
            content += "## Tech Stack\n"
            for tech in rules["tech_stack"]:
                content += f"- {tech}\n"
            content += "\n"
        
        if rules["decisions"]:
            content += "## Key Decisions\n"
            for decision in rules["decisions"]:
                content += f"- {decision}\n"
            content += "\n"
        
        if rules["patterns"]:
            content += "## Code Patterns\n"
            for pattern in rules["patterns"]:
                content += f"- {pattern}\n"
            content += "\n"
        
        if rules["constraints"]:
            content += "## Constraints\n"
            for constraint in rules["constraints"]:
                content += f"- {constraint}\n"
            content += "\n"
        
        content += f"\n_Last updated: {datetime.now().isoformat()}_\n"
        return content
    
    def format_trae_rules(self, rules: Dict[str, List[str]]) -> str:
        """Generate .trae/rules.md format"""
        content = "# Project Rules\n\n"
        content += "This file is auto-generated by OpenMem.\n\n"
        
        if rules["tech_stack"]:
            content += "## Tech Stack\n\n"
            for tech in rules["tech_stack"]:
                content += f"- {tech}\n"
            content += "\n"
        
        if rules["decisions"]:
            content += "## Key Decisions\n\n"
            for decision in rules["decisions"]:
                content += f"- {decision}\n"
            content += "\n"
        
        content += f"\n---\n_Last updated: {datetime.now().isoformat()}_\n"
        return content
    
    def format_copilot_rules(self, rules: Dict[str, List[str]]) -> str:
        """Generate .github/copilot-instructions.md format"""
        content = "# Copilot Instructions\n\n"
        content += "This file is auto-generated by OpenMem.\n\n"
        
        if rules["tech_stack"]:
            content += "## Tech Stack\n\n"
            for tech in rules["tech_stack"]:
                content += f"- {tech}\n"
            content += "\n"
        
        if rules["patterns"]:
            content += "## Code Patterns\n\n"
            for pattern in rules["patterns"]:
                content += f"- {pattern}\n"
            content += "\n"
        
        return content
    
    def format_project_rules(self, rules: Dict[str, List[str]]) -> str:
        """Generate PROJECT_RULES.md format"""
        content = "# Project Rules\n\n"
        content += "This file is auto-generated by OpenMem.\n\n"
        
        if rules["tech_stack"]:
            content += "## Tech Stack\n\n"
            for tech in rules["tech_stack"]:
                content += f"- {tech}\n"
            content += "\n"
        
        if rules["decisions"]:
            content += "## Key Decisions\n\n"
            for decision in rules["decisions"]:
                content += f"- {decision}\n"
            content += "\n"
        
        if rules["patterns"]:
            content += "## Code Patterns\n\n"
            for pattern in rules["patterns"]:
                content += f"- {pattern}\n"
            content += "\n"
        
        if rules["constraints"]:
            content += "## Constraints\n\n"
            for constraint in rules["constraints"]:
                content += f"- {constraint}\n"
            content += "\n"
        
        if rules["todos"]:
            content += "## Pending TODOs\n\n"
            for todo in rules["todos"]:
                content += f"- [ ] {todo}\n"
            content += "\n"
        
        content += f"\n---\n_Last updated: {datetime.now().isoformat()}_\n"
        return content
    
    def write_rules_file(self, filepath: str, content: str):
        """Write rules file"""
        full_path = os.path.join(self.project_path, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)
        
        print(f"✅ Updated: {full_path}")
